apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  databutton.com/version: 0.24.5
commonLabels:
  databutton.com/project_id: 7fc5b004-a1f1-4cdf-9103-ecc3f6608dbf
kind: Kustomization
namespace: 7fc5b004-a1f1-4cdf-9103-ecc3f6608dbf
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- mapping.yaml
